# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WilsonDev' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WilsonDev

  target 'WilsonDevTests' do
    inherit! :search_paths
    pod 'AFNetworking', '~> 3.1.0'
  end

  target 'WilsonDevUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
