# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'WilsonDev' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WilsonDev

  inherit! :search_paths
  pod 'SDAutoLayout', '~> 2.2.0'
  pod 'Masonry', '~> 1.1.0'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'Realm', '~> 3.1.0'

  target 'WilsonDevUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
