# Uncomment the next line to define a global platform for your project
# platform :iOS, '8.0'

target 'WilsonDev' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WilsonDev

  target 'WilsonDevTests' do
    inherit! :search_paths
    pod 'SDAutoLayout', '~> 2.2.0'
    pod 'Masonry', '~> 1.1.0'
    pod 'AFNetworking', '~> 3.1.0'
  end

  target 'WilsonDevUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
